# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: robobabel
  password:
  host: localhost

development:
  <<: *default
  database: robobabel_developement

test:
  <<: *default
  database: robobabel_test

production:
  <<: *default
  database: robobabel
  host: ENV['DB_HOST']
